### ISSUE TITLE
Dateiupload-URL matcht

### ISSUE THREAD

**Issue by raffiii** [philippweinmann/iliasLogin#1]
Das erste url-pattern matcht wohl auch bei z.B. Dateiuploads in Postfächern, was es ohne deaktivieren unmöglich macht, dort etwas hochzuladen. Für welche Seiten ist die eigentlich gedacht? Lässt sich das weiter einschränken?

https://github.com/philippweinmann/iliasLogin/blob/930a733ebed7c9c16825fe3a37a18048cabf9123/iliasLogin.js#L14

**Comment by philippweinmann** [comment]
Hallo @raffiii  Vielen Dank für deine Issue! Ich habe es mir angesehen, und ich habe es glaube ich verbessert. Jetzt wird nicht mehr weitergeleitet sondern geclickt. Die hoffnung ist, das das element nur clickable ist, wenn man nicht eingeloggt ist. Falls nicht , werde ich diese URL vollständig entfernen, alle Bugs kommen um Moment wergen ihr.

**Comment by philippweinmann** [comment]
Ich werde die Extension nun ausführlich Testen und dann updaten!

**Comment by philippweinmann** [comment]
Extension ist geupdated. Bitte bescheid geben ob es funktioniert hat @raffiii!

**Comment by philippweinmann** [comment]
Ich schließe die Issue, weil seit zwei Wochen alles zu funktionieren scheint.
